# Docker Compose file deploying infrastructure services
version: "3.8"
services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - homepage:/app/config
    ports:
      - "3333:3000"
    restart: always

  nginx:
    image: jc21/nginx-proxy-manager:latest
    volumes:
      - nginx-proxy-manager:/data
      - nginx-certs:/etc/letsencrypt
    ports:
      - "443:443"
      - "80:80"
      - "81:81"
    restart: always

  unifi-db:
    image: mongo:7.0.11
    volumes:
      - unifi-db:/data/db
      - /home/tadmin/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    restart: always

  unifi-controller:
    image: linuxserver/unifi-network-application:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - MONGO_USER=unifi
      - MONGO_PASS=unifuck
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
    volumes:
      - unifi:/config
    ports:
      - "10001:10001/udp"
      - "3478:3478/udp"
      - "8080:8080"
      - "8443:8443"
    restart: always

volumes:
  homepage:
  nginx-proxy-manager:
  nginx-certs:
  unifi-db:
  unifi: