# Docker Compose file deploying infrastructure services
version: "3.8"
services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - type: volume
        source: Homepage
        target: /app/config
    ports:
      - "3333:3000"
    restart: always

  nginx:
    image: jc21/nginx-proxy-manager:latest
    volumes:
      - type: volume
        source: Nginx
        target: /data
      - type: volume
        source: Nginx
        target: /etc/letsencrypt
    ports:
      - "443:443"
      - "80:80"
      - "81:81"
    restart: always

  unifi:
    image: ghcr.io/goofball222/unifi:latest
    links:
      - mongo
    volumes:
      - type: volume
        source: Unifi
        target: /usr/lib/unifi/cert
      - type: volume
        source: Unifi
        target: /usr/lib/unifi/data
      - type: volume
        source: Unifi
        target: /usr/lib/unifi/logs
    ports:
      - "3478:3478/udp"
      - "8080:8080"
      - "8443:8443"
      - "8880:8880"
      - "8843:8843"
    environment:
      - TZ=Europe/Amsterdam
      - DB_MONGO_LOCAL=false
      - DB_MONGO_URI=mongodb://mongo:27017/unifi
      - STATDB_MONGO_URI=mongodb://mongo:27017/unifi_stat
      - UNIFI_DB_NAME=unifi
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - type: volume
        source: UnifiDB
        target: /data/db
    restart: unless-stopped

  adguardhome:
    image: adguard/adguardhome
    ports:
      - "53:53"
      - "784:784"
      - "853:853"
      - "3300:3000"
      - "88:80"
      - "4443:443"
    volumes:
      - type: volume
        source: Adguard
        target: /opt/adguardhome/work
      - type: volume
        source: Adguard
        target: /opt/adguardhome/conf
    restart: unless-stopped

volumes:
  Adguard:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/Adguard"
  Homepage:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/Homepage"
  Nginx:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/Nginx"
  Unifi:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/Unifi"
  UnifiDB:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/Unifi-DB"