# Docker Compose file deploying infrastructure services
version: "3.8"
services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - type: volume
        source: Homepage
        target: /app/config
    ports:
      - "3333:3000"
    restart: always

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    volumes:
      - type: volume
        source: Nginx
        target: /data
      - type: volume
        source: Nginx
        target: /etc/letsencrypt
    ports:
      - "443:443"
      - "80:80"
      - "81:81"
    restart: always

volumes:
  Homepage:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/Homepage"
  Nginx:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/Nginx"