# Docker Compose file deploying infrastructure services
version: "3.8"
services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - type: volume
        source: infrastructure_data
        target: /app/config
        volume:
          subpath: homepage_data
    ports:
      - "3333:3333"
    restart: always

  nginx:
    image: jc21/nginx-proxy-manager:latest
    volumes:
      - type: volume
        source: infrastructure_data
        target: /data
        volume:
          subpath: nginx_data
      - type: volume
        source: infrastructure_data
        target: /etc/letsencrypt
        volume:
          subpath: nginx_cert
    ports:
      - "443:443"
      - "80:80"
      - "81:81"
    restart: always

  unifi-controller:
    image: linuxserver/unifi-controller:latest
    volumes:
      - type: volume
        source: infrastructure_data
        target: /config
        volume:
          subpath: unifi_data
    ports:
      - "10001:10001"
      - "3478:3478"
      - "8080:8080"
      - "8443:8443"
    restart: always

volumes:
  infrastructure_data: