# Docker Compose file deploying infrastructure services
version: "3.8"
services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - type: volume
        source: Homepage
        target: /app/config
    ports:
      - "3333:3000"
    restart: always

  unifi:
    image: ghcr.io/goofball222/unifi:latest
    links:
      - mongo
    volumes:
      - type: volume
        source: Unifi
        target: /usr/lib/unifi/cert
      - type: volume
        source: Unifi
        target: /usr/lib/unifi/data
      - type: volume
        source: Unifi
        target: /usr/lib/unifi/logs
    ports:
      - "3478:3478/udp"
      - "8080:8080"
      - "8443:8443"
      - "8880:8880"
      - "8843:8843"
    environment:
      - TZ=Europe/Amsterdam
      - DB_MONGO_LOCAL=false
      - DB_MONGO_URI=mongodb://mongo:27017/unifi
      - STATDB_MONGO_URI=mongodb://mongo:27017/unifi_stat
      - UNIFI_DB_NAME=unifi
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - type: volume
        source: UnifiDB
        target: /data/db

volumes:
  Homepage:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/Homepage"
  Unifi:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/Unifi"
  UnifiDB:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/Unifi-DB"