# Docker Compose file deploying infrastructure services
version: "3.8"
services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - type: volume
        source: Homepage
        target: /app/config
    ports:
      - "3333:3000"
    restart: always

  nginx:
    image: jc21/nginx-proxy-manager:latest
    volumes:
      - type: volume
        source: Nginx
        target: /data
      - type: volume
        source: Nginx
        target: /etc/letsencrypt
    ports:
      - "443:443"
      - "80:80"
      - "81:81"
    restart: always

  # unifi-db:
  #   image: mongo:7.0.11
  #   volumes:
  #     - type: volume
  #       source: Unifi-DB
  #       target: /data/db
  #   ports:
  #     - "27017:27017"
  #   restart: always

  unifi-controller:
    image: linuxserver/unifi-controller:latest
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=Europe/Amsterdam
      # - MONGO_USER=unifi
      # - MONGO_PASS=unifuck
      # - MONGO_HOST=unifi-db
      # - MONGO_PORT=27017
      # - MONGO_DBNAME=unifi
    volumes:
      - type: volume
        source: Unifi
        target: /config
    ports:
      - "10001:10001/udp"
      - "3478:3478/udp"
      - "8080:8080"
      - "8443:8443"
    restart: always

volumes:
  Homepage:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/Homepage"
  Nginx:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/Nginx"
  # Unifi-DB:
  #   driver: local
  #   driver_opts:
  #     type: nfs
  #     o: addr=10.10.1.7,rw
  #     device: ":/mnt/Array/Docker/Unifi-DB"
  Unifi:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/Unifi"