- name: Install Docker
  hosts: DOCKER
  tasks:
  
    - name: Download install script
      become: true
      ansible.builtin.shell: wget https://raw.githubusercontent.com/Gerruhtz/homelab/main/scripts/install_docker.sh -O install_docker.sh
      args:
        chdir: /home/tadmin/

    - name: Make install script executable
      become: true
      ansible.builtin.shell: sudo chmod +x /home/tadmin/install_docker.sh

    - name: Run Docker install script
      become: true
      ansible.builtin.shell: /home/tadmin/install_docker.sh

    - name: Create /mnt/Media directory
      become: true
      ansible.builtin.file:
        path: /mnt/Media
        state: directory

    - name: Mount NFS share
      become: true
      ansible.builtin.shell: echo "10.10.1.7:/mnt/Array/Media /mnt/Media nfs defaults 0 0" >> /etc/fstab && sudo systemctl daemon-reload && sudo mount -a