- name: Deploying base configuration
  hosts: VID20
  tasks:

    - name: Add Cloudflare DNS server
      become: true
      ansible.builtin.shell: echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf /dev/null

    - name: Updating APT cache
      become: true
      ansible.builtin.apt:
        update_cache: yes

    - name: Installing packages
      become: true
      ansible.builtin.apt:
        pkg:
        - nano
        - git
        - qemu-guest-agent
        - iputils-ping

    - name: Enabling services
      become: true
      ansible.builtin.service:
        name: qemu-guest-agent
        enabled: yes