- name: Implement basic security features
  hosts: VID20
  tasks:
    - name: Remove password for root
      become: true
      ansible.builtin.shell: sudo passwd -d root
    - name: Install public SSH key
      ansible.builtin.shell: cat "{{ public_ssh_key }}" >> .ssh/authorized_keys
    - name: Disable SSH password authentication
      ansible.builtin.shell: sudo sed -E -i 's|^#?(PasswordAuthentication)\s.*|\1 no|' /etc/ssh/sshd_config | if ! grep '^PasswordAuthentication\s' /etc/ssh/sshd_config; then echo 'PasswordAuthentication no' | sudo tee -a /etc/ssh/sshd_config; fi
    - name: Disable SSH access for root
      ansible.builtin.shell: $ sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
    - name: Restart SSH service
      become: true
      ansible.builtin.shell: sudo systemctl restart ssh