- name: Deploying base configuration
  hosts: VID20
  tasks:

    - name: Updating APT cache
      become: true
      ansible.builtin.apt:
        update_cache: yes

    - name: Installing packages
      become: true
      ansible.builtin.apt:
        pkg:
        - nano
        - git
        - qemu-guest-agent

    - name: Enabling services
      become: true
      ansible.builtin.service:
        name: qemu-guest-agent
        enabled: yes