- name: Deploying base configuration
  hosts: VID10:VID20
  tasks:

    - name: Updating APT cache
      become: true
      ansible.builtin.apt:
        update_cache: yes
        upgrade: "dist"

    - name: Installing packages
      become: true
      ansible.builtin.apt:
        name:
        - nano
        - git
        - qemu-guest-agent
        - iputils-ping
        - nfs-common

    - name: Enabling services
      become: true
      ansible.builtin.service:
        name: qemu-guest-agent
        enabled: yes

    - name: Remove password for root
      become: true
      ansible.builtin.shell: sudo passwd -d root

    - name: Install public SSH key
      ansible.builtin.shell: echo "{{ public_ssh_key }}" >> ~/.ssh/authorized_keys

    - name: Disable SSH password authentication
      ansible.builtin.shell: sudo sed -E -i 's|^#?(PasswordAuthentication)\s.*|\1 no|' /etc/ssh/sshd_config ; if ! grep '^PasswordAuthentication\s' /etc/ssh/sshd_config; then echo 'PasswordAuthentication no' | sudo tee -a /etc/ssh/sshd_config; fi
    
    - name: Disable SSH access for root
      become: true
      ansible.builtin.shell: sudo sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
      
    - name: Restart SSH service
      become: true
      ansible.builtin.shell: sudo systemctl restart ssh