VID10:
  hosts:
    AUTOMATION:
      ansible_host: 10.10.10.9
    DOCKER:
      ansible_host: 10.10.10.10
    MEDIA:
      ansible_host: 10.10.10.11

VID20:
  hosts:
    TEST:
      ansible_host: 10.10.20.230