# Docker Compose file deploying monitoring services
version: "3.8"
services:

  influxdb:
    image: influxdb:latest
    volumes:
      - type: volume
        source: InfluxDB
        target: /var/lib/influxdb2
      - type: volume
        source: InfluxDB
        target: /etc/influxdb2
    ports:
      - "8086:8086"
    restart: always

  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - type: volume
        source: Grafana
        target: /var/lib/grafana
    ports:
      - "3000:3000"
    restart: always

  uptime-kuma:
    image: louislam/uptime-kuma
    volumes:
      - type: volume
        source: Uptime-Kuma
        target: /app/data
    ports:
      - "3001:3001"
    restart: always

volumes:
  InfluxDB:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/InfluxDB"
  Grafana:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/Grafana"
  Uptime-Kuma:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.1.7,rw
      device: ":/mnt/Array/Docker/Uptime-Kuma"