# Docker Compose file deploying monitoring services
version: "3.8"
services:

  influxdb:
    image: influxdb:latest
    volumes:
      - monitoring_data/influx-data:/var/lib/influxdb2
      - monitoring_data/influx-config:/etc/influxdb2
    ports:
      - "8086:8086"
    restart: always

  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - monitoring_data/grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always

  uptime-kuma:
    image: louislam/uptime-kuma
    volumes:
      - monitoring_data/uptime-data:/app/data
    ports:
      - "3001:3001"
    restart: always

volumes:
  monitoring_data:
  monitoring_config: