# Docker Compose file deploying monitoring services
version: "3.8"
services:

  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb:/var/lib/influxdb2
      - influxdb:/etc/influxdb2
    ports:
      - "8086:8086"
    restart: always

  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always

  uptime-kuma:
    image: louislam/uptime-kuma
    volumes:
      - uptime-kuma:/app/data
    ports:
      - "3001:3001"
    restart: always

volumes:
  influxdb:
  grafana:
  uptime-kuma: