name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  Pull:
    runs-on: "self-hosted"

    steps:
      - name: Pull repo
        uses: actions/checkout@v4
        with:
            repository: Gerruhtz/homelab
            path: homelab