# GitHub Actions workflow to run 'terraform apply' after push to main
# Only runs when a change to .tf files is pushed to main

name: Deploy Terraform

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.tfvars'

env:
  TF_DIRECTORY: ${{ vars.TF_WORKING_DIRECTORY }}

jobs:
    terraform:
        name: "Test, plan and apply Terraform changes"

        runs-on: 'self-hosted'
        steps:

            - name: Checkout
              uses: actions/checkout@v4

            - name: Terraform Plan
              working-directory: ${{ vars.TF_WORKING_DIRECTORY }}
              run: terraform plan -no-color -input=false
              continue-on-error: true

            - name: Terraform Apply
              working-directory: ${{ vars.TF_WORKING_DIRECTORY }}
              run: terraform apply -auto-approve -input=false