# GitHub Actions workflow to run 'terraform apply' after push to main
# Only runs when a change to .tf files is pushed to main

name: "Deploy infrastructure"

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '!**/DIMM-SWARM*.tf'

env:
  WORKING_DIRECTORY: ${{ vars.LOCAL_WORKING_DIRECTORY }}
  TF_DIRECTORY: ${{ vars.TF_WORKING_DIRECTORY }}
  ANSI_DIRECTORY: ${{ vars.ANSI_WORKING_DIRECTORY }}

jobs:
    auto-pull:
      name: Pull homelab repository
      runs-on: 'self-hosted'
      steps:
        - uses: actions/checkout@v4
        - run: git pull
          working-directory: ${{ vars.LOCAL_WORKING_DIRECTORY }}

    terraform:
        name: Deploy infrastructure
        runs-on: 'self-hosted'
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Terraform Plan
              working-directory: ${{ vars.TF_WORKING_DIRECTORY }}
              run: terraform plan -input=false
              continue-on-error: true

            - name: Terraform Apply
              working-directory: ${{ vars.TF_WORKING_DIRECTORY }}
              run: terraform apply -auto-approve -input=false

    ansible:
      name: Configure infrastructure
      runs-on: 'self-hosted'
      needs: terraform
      steps:
            - name: Wait for 1 minute
              run: sleep 1m

            - name: Run Ansible playbook 'base_config.yaml'
              working-directory: ${{ vars.ANSI_WORKING_DIRECTORY }}
              run: ansible-playbook base_config.yaml -i inventory.yaml