# GitHub Actions workflow to run 'terraform apply' after push to main
# Only runs when a change to Kubernetes files is pushed to main

name: "Deploy Docker server"

on:
  push:
    branches:
      - main
    paths:
      - '**/DIMM-K8S*.tf'

env:
  TF_DIRECTORY: ${{ vars.TF_WORKING_DIRECTORY }}
  ANSI_DIRECTORY: ${{ vars.ANSI_WORKING_DIRECTORY }}

jobs:
    auto-pull:
      name: Pull homelab repository
      runs-on: 'self-hosted'
      steps:
        - uses: actions/checkout@v4
        - run: git pull
          working-directory: ${{ vars.LOCAL_WORKING_DIRECTORY }}
          
    terraform:
        name: Deploy infrastructure
        runs-on: 'self-hosted'
        needs: auto-pull
        steps:
            - name: Terraform Plan
              working-directory: ${{ vars.TF_WORKING_DIRECTORY }}
              run: terraform plan -input=false
              continue-on-error: true

            - name: Terraform Apply
              working-directory: ${{ vars.TF_WORKING_DIRECTORY }}
              run: terraform apply -auto-approve -input=false

    ansible:
      name: Configure Kubernetes node
      runs-on: 'self-hosted'
      needs: terraform
      steps:
            - name: Wait for 1 minute
              run: sleep 1m

            - name: Run Ansible playbook 'base_config.yaml'
              working-directory: ${{ vars.ANSI_WORKING_DIRECTORY }}
              run: ansible-playbook base_config.yaml -i inventory.yaml

            - name: Run Ansible playbook 'base_kubernetes.yaml'
              working-directory: ${{ vars.ANSI_WORKING_DIRECTORY }}
              run: ansible-playbook base_kubernetes.yaml -i inventory.yaml