name: Sync repository

on:
  push:
    branches:
      - main

jobs:
  auto-pull:
    name: Pull homelab
    runs-on: 'self-hosted'
    steps:
      - uses: actions/checkout@v4
      - run: git pull
        working-directory: /home/tadmin/homelab