name: Sync repository

on:
  push:
    branches:
      - main

env:
  WORKING_DIRECTORY: ${{ vars.LOCAL_WORKING_DIRECTORY }}

jobs:
  auto-pull:
    name: Pull homelab
    runs-on: 'self-hosted'
    steps:
      - uses: actions/checkout@v4
      - run: git pull
        working-directory: $WORKING_DIRECTORY